import type { IProgram } from "../models/Program";

export const programs: IProgram[] = [
  {
    gender: "Boys",
    teamName: "Falcons",
    birthyear: "2012",
    league: "Youth League",
    coachName: "John Smith",
    coachEmail: "john.smith@example.com",
  },
  {
    gender: "Girls",
    teamName: "Tigers",
    birthyear: "2011",
    league: "Junior League",
    coachName: "Mary Johnson",
    coachEmail: "mary.johnson@example.com",
  },
  {
    gender: "Boys",
    teamName: "Eagles",
    birthyear: "2010",
    league: "Youth League",
    coachName: "Michael Brown",
    coachEmail: "michael.brown@example.com",
  },
  {
    gender: "Girls",
    teamName: "Panthers",
    birthyear: "2013",
    league: "Junior League",
    coachName: "Linda Davis",
    coachEmail: "linda.davis@example.com",
  },
  {
    gender: "Boys",
    teamName: "Sharks",
    birthyear: "2012",
    league: "Youth League",
    coachName: "James Wilson",
    coachEmail: "james.wilson@example.com",
  },
  {
    gender: "Girls",
    teamName: "Lions",
    birthyear: "2011",
    league: "Junior League",
    coachName: "Patricia Martinez",
    coachEmail: "patricia.martinez@example.com",
  },
  {
    gender: "Boys",
    teamName: "Wolves",
    birthyear: "2010",
    league: "Youth League",
    coachName: "Robert Anderson",
    coachEmail: "robert.anderson@example.com",
  },
  {
    gender: "Girls",
    teamName: "Hawks",
    birthyear: "2013",
    league: "Junior League",
    coachName: "Barbara Thomas",
    coachEmail: "barbara.thomas@example.com",
  },
  {
    gender: "Boys",
    teamName: "Raptors",
    birthyear: "2012",
    league: "Youth League",
    coachName: "William Taylor",
    coachEmail: "william.taylor@example.com",
  },
  {
    gender: "Girls",
    teamName: "Cobras",
    birthyear: "2011",
    league: "Junior League",
    coachName: "Elizabeth Moore",
    coachEmail: "elizabeth.moore@example.com",
  },
  {
    gender: "Boys",
    teamName: "Dragons",
    birthyear: "2010",
    league: "Youth League",
    coachName: "David Jackson",
    coachEmail: "david.jackson@example.com",
  },
  {
    gender: "Girls",
    teamName: "Phoenix",
    birthyear: "2013",
    league: "Junior League",
    coachName: "Jennifer White",
    coachEmail: "jennifer.white@example.com",
  },
  {
    gender: "Boys",
    teamName: "Titans",
    birthyear: "2012",
    league: "Youth League",
    coachName: "Charles Harris",
    coachEmail: "charles.harris@example.com",
  },
  {
    gender: "Girls",
    teamName: "Vipers",
    birthyear: "2011",
    league: "Junior League",
    coachName: "Susan Clark",
    coachEmail: "susan.clark@example.com",
  },
  {
    gender: "Boys",
    teamName: "Cheetahs",
    birthyear: "2010",
    league: "Youth League",
    coachName: "Joseph Lewis",
    coachEmail: "joseph.lewis@example.com",
  },
  {
    gender: "Girls",
    teamName: "Panthers II",
    birthyear: "2013",
    league: "Junior League",
    coachName: "Margaret Robinson",
    coachEmail: "margaret.robinson@example.com",
  },
  {
    gender: "Boys",
    teamName: "Hornets",
    birthyear: "2012",
    league: "Youth League",
    coachName: "Daniel Walker",
    coachEmail: "daniel.walker@example.com",
  },
  {
    gender: "Girls",
    teamName: "Eagles II",
    birthyear: "2011",
    league: "Junior League",
    coachName: "Nancy Hall",
    coachEmail: "nancy.hall@example.com",
  },
  {
    gender: "Boys",
    teamName: "Mustangs",
    birthyear: "2010",
    league: "Youth League",
    coachName: "Matthew Allen",
    coachEmail: "matthew.allen@example.com",
  },
  {
    gender: "Girls",
    teamName: "Falcons II",
    birthyear: "2013",
    league: "Junior League",
    coachName: "Karen Young",
    coachEmail: "karen.young@example.com",
  },
];
